import React from 'react';
import { SkinReport } from '../types';

const Report: React.FC<{ report: SkinReport; onReset: () => void; onDiscuss: () => void; }> = ({ report, onReset, onDiscuss }) => {
  return (
    <>
      <div id="report-content" className="w-full max-w-3xl bg-white p-8 md:p-12 rounded-2xl shadow-2xl border border-gray-100 font-sans">
        <div className="flex justify-between items-start mb-10 border-b border-gray-200 pb-6">
          <div>
            <h1 className="text-3xl md:text-4xl font-bold text-gray-800">Personal Skin Report</h1>
            <p className="text-gray-500 mt-2">Generated by Medzeal AI</p>
          </div>
          <div className="text-right flex-shrink-0 ml-4">
            <p className="font-semibold text-gray-800">{report.name}</p>
            <p className="text-sm text-gray-600">{report.phone}</p>
            <p className="text-sm text-gray-600 mt-1">{report.date}</p>
          </div>
        </div>

        <div className="bg-blue-50 border border-blue-200 rounded-xl p-6 mb-8">
          <h2 className="text-xl font-semibold text-blue-800 mb-3 flex items-center">
            <span className="mr-3 text-2xl">⭐</span> AI Summary
          </h2>
          <p className="text-gray-700 leading-relaxed">{report.summary}</p>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          <div className="bg-gray-50 border border-gray-200 rounded-xl p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4 flex items-center">
              <span className="mr-3 text-2xl">⚠️</span> Detected Issues
            </h2>
            {report.issues.length > 0 ? (
                <div className="space-y-4">
                  {report.issues.map((issue, index) => (
                    <div key={index} className="text-gray-700">
                      <p className="font-semibold">{issue.issue}</p>
                      <p className="text-sm text-gray-600">{issue.description}</p>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-gray-600">No significant issues were detected based on the analysis.</p>
              )}
          </div>

          <div className="bg-gray-50 border border-gray-200 rounded-xl p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4 flex items-center">
              <span className="mr-3 text-2xl">💊</span> Medzeal Recommendations
            </h2>
            {report.recommendations.length > 0 ? (
                <div className="space-y-4">
                  {report.recommendations.map((rec, index) => (
                    <div key={index} className="text-gray-700">
                      <p className="font-semibold">{rec.treatment}</p>
                      <p className="text-sm text-gray-600">{rec.description}</p>
                    </div>
                  ))}
                </div>
              ) : (
                  <p className="text-gray-600">General skincare advice applies. No specific treatments are recommended at this time.</p>
              )}
          </div>
        </div>
      </div>
      <div className="w-full max-w-3xl text-center mt-8">
         <div className="flex justify-center gap-4 flex-wrap">
            <button
                onClick={onDiscuss}
                className="px-6 py-3 bg-green-600 text-white font-semibold rounded-full shadow-md hover:bg-green-700 transition-all duration-300"
            >
                Send to WhatsApp
            </button>
            <button
                onClick={onReset}
                className="px-6 py-3 bg-blue-600 text-white font-semibold rounded-full shadow-md hover:bg-blue-700 transition-all duration-300"
            >
                Start New Check-up
            </button>
        </div>
        <p className="text-sm text-gray-500 mt-6 px-4">This is a preliminary AI analysis and not a substitute for a professional dermatological examination.</p>
      </div>
    </>
  );
};

export default Report;
